# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
  - stage: Download_Dependency
    displayName: Download Dependency
    jobs:
      - deployment: Prepare_Env
        pool:
          vmImage: ubuntu-latest
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.9'

                # - script: |
                #     pip install --upgrade pip
                #     pip install artifacts-keyring

                - task: PipAuthenticate@1
                  inputs:
                    artifactFeeds: gsoertsz/cli-bumpversion-example-release

                - script: |
                    pip install -vvv hello --index-url $(PIP_INDEX_URL)

                - script: |
                    hello --help
