# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pr: none

parameters:
- name: feed
  displayName: The artefact feed (project/feedname only)
  type: string
- name: version
  displayName: The version we want
  type: string
  default: ''

stages:
  - stage: Download_Dependency
    displayName: Download Dependency
    jobs:
      - deployment: Download_And_Execute_CLI
        pool:
          vmImage: ubuntu-latest
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.9'

                - task: PipAuthenticate@1
                  inputs:
                    artifactFeeds: ${{ parameters.feed }}

                - task: CmdLine@2
                  displayName: Install specified version
                  condition: ne('${{ parameters.version }}', '')
                  inputs:
                    script: |
                      pip install -vvv cli-bumpversion-example==${{ parameters.version }} --index-url $(PIP_INDEX_URL)

                - task: CmdLine@2
                  displayName: Install latest version
                  condition: eq('${{ parameters.version }}', '')
                  inputs:
                    script: |
                      pip install -vvv cli-bumpversion-example --index-url $(PIP_INDEX_URL)

                - script: |
                    hello --help
